<?php

use Dompdf\Dompdf;

class Reports {

    use Controller;

    public function index(){
        $this->view('admin/reports');
    }

    public function generate() {
        // Assume $_POST data is sanitized and validated properly
        $from = $_POST['from'];
        $to = $_POST['to'];

        $appointmentModel = new AppointmentsModel();
        $appointmentCount = $appointmentModel->countAllAppointments($from, $to);
        $appointmentIncome = $appointmentModel->incomeFromAppointments($from, $to);
        $cancelledCount = $appointmentModel->countAppointmentsByStatus('cancelled', $from, $to);
        $finishedCount = $appointmentModel->countAppointmentsByStatus('finished', $from, $to);

        $html = $this->prepareHTMLReport($appointmentCount, $appointmentIncome, $cancelledCount, $finishedCount, $from, $to);
        

        // Generate PDF and stream it directly to the browser
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        $dompdf->stream("Appointment report {$from} to {$to}.pdf", ["Attachment" => false]);
    }

    private function prepareHTMLReport($appointmentCount, $appointmentIncome, $cancelledCount, $finishedCount, $from, $to) {
        $reportDate = date('Y-m-d');
        $html = <<<HTML
        <html>
        <head>
            <style>
                body { font-family: 'Helvetica', sans-serif; font-size: 12px; padding: 50px; }
                h1 { text-align: center; }
                h3 { font-weight:normal; }
                table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                th, td { border: 1px solid black; padding: 8px; text-align: left; font-size: 15px; }
                th { background-color: #f2f2f2; }
            </style>
        </head>
        <body>
            <h1>Appointment Report</h1>
            <br><br><br>
            <h3><b>From:</b>    {$from}</h3>
            <h3><b>To:</b>      {$to}</h3>
            <table>
                <thead>
                    <tr>
                        <th>Measure</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr><td>Total Appointments</td><td>{$appointmentCount}</td></tr>
                    <tr><td>Total Income</td><td>{$appointmentIncome}</td></tr>
                    <tr><td>Cancelled Appointments</td><td>{$cancelledCount}</td></tr>
                    <tr><td>Finished Appointments</td><td>{$finishedCount}</td></tr>
                </tbody>
            </table>
            <p>This report was generated by the system on {$reportDate}.</p>
        </body>
        </html>
        HTML;

        return $html;
    }
}

?>
